version: "3.8"

services:
  django:
    build: ./backend
    container_name: dev-django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    volumes:
      - ./backend/:/srv/app
      - static:/srv/app/static
      - media:/srv/app/media
    depends_on:
      - db
  db:
    image: postgres:16.1-alpine
    container_name: dev-db
    ports:
      - 5432:5432
    env_file: ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailcatcher:
    image: schickling/mailcatcher
    container_name: dev-mailcatcher
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  node_modules:
  postgres_data:
  media:
  static:
