from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema

add_card_request_body = openapi.Schema(
    type=openapi.TYPE_OBJECT,
    required=["payment_method_id"],
    properties={
        "payment_method_id": openapi.Schema(
            type=openapi.TYPE_STRING,
            description="The ID of the payment method (card) generated by Stripe.",
            example="pm_1N2xY2P74YGSrBH5frvjVUEO"
        )
    }
)

add_card_responses = {
    200: openapi.Response(
        description="Card added successfully",
        examples={
            "application/json": {
                "message": "Card added successfully."
            }
        }
    ),
    400: openapi.Response(
        description="Validation error or Stripe error",
        examples={
            "application/json": {
                "error": "Payment method ID is required."
            }
        }
    )
}

add_card_swagger = swagger_auto_schema(
        operation_summary="Add a Payment Method (Card)",
        operation_description="Attach a payment method (card) to the authenticated user's Stripe account.",
        request_body=add_card_request_body,
        responses=add_card_responses
)